Unity Scene 추가
GAMPOT-DEV/TEAM_2 pull request #15
Opened 2022-03-13 07:41 UTC by hhtboy

Asset폴더 내에 gitignore가 Unity Scene을 무시하는 오류가 있어서 gitignore을 삭제했습니다.
추가로 삭제되었던 Scene을 추가하였습니다.

2022-03-13 07:49 UTC, ch-0012 approved these changes

2022-03-14 06:32 UTC, hhtboy commented
.

2022-03-14 06:53 UTC, Pumandu requested changes
.

2022-03-14 06:54 UTC, Pumandu approved these changes

2022-03-14 06:54 UTC, merged